; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_flags = 
	-D LV_CONF_SKIP
	-D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE
	-D LV_USE_DEMO_WIDGETS
lib_deps = 
	lvgl@9.3
lib_archive = false

[env:rp2040-pico]
platform = raspberrypi
board = pico
framework = arduino
upload_port = 22
build_flags = 
	${env.build_flags}
    -D LGFX_USE_V1
lib_deps = 
	${env.lib_deps}
	lovyan03/LovyanGFX@^1.2.19
lib_ignore = 
	Arduino_H7_Video

[env:native]
platform = native
test_framework = unity
test_build_src = true
lib_deps =
lib_ignore =
	lvgl
build_src_filter =
	-<*>
	+<app/app_state.cpp>
	+<events/event_queue.cpp>
build_flags =
	-std=gnu++17
	-I include
	-I src

[env:native-sim]
platform = native
extra_scripts = pre:scripts/native_sim_env.py
lib_deps =
	${env.lib_deps}
build_src_filter =
	-<*>
	+<app/app_state.cpp>
	+<events/event_queue.cpp>
	+<ui/home_screen.cpp>
	+<ui/bias_settings.cpp>
	+<ui/ui_router.cpp>
	+<system/display_port_sim.cpp>
	+<sim/sim_main.cpp>
build_flags =
	${env.build_flags}
	-std=gnu++17
	-D LV_USE_SDL=1
	-I include
	-I src
	-I sim/include
